
package Swing.AdminUsr;

import Swing.AdminUsr.EleccionDeCuenta;
import Swing.Inicializador;
import Swing.LogIn;
import Swing.Menu.Menu;
import javax.swing.JOptionPane;

/**
 *
 * @author jomel
 */
public class BuscadorDeUsuario extends javax.swing.JDialog {
    private char caracter;
    private boolean caso;
    private Usuarios.Usuario UsuarioIngresado;
    private Menu menu;
    /**
     * Creates new form BuscadorDeUsuario
     */
    public BuscadorDeUsuario(java.awt.Frame parent, boolean modal, boolean caso,
            Usuarios.Usuario UsuarioIngresado, Menu menu) {
        super(parent, modal);
        initComponents();
        caracter = TextoContra.getEchoChar();
        this.caso = caso;
        this.menu = menu;
        this.UsuarioIngresado = UsuarioIngresado;
        this.setLocation(350,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextoContra = new javax.swing.JPasswordField();
        Mostrar = new javax.swing.JToggleButton();
        LogIn = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LogIn1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Java Ticket");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Usuario:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        TextoUsuario.setBackground(new java.awt.Color(30, 30, 30));
        TextoUsuario.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        TextoUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(TextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 330, 50));

        jLabel2.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Contraseña:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        TextoContra.setBackground(new java.awt.Color(30, 30, 30));
        TextoContra.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        TextoContra.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(TextoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 290, 50));

        Mostrar.setBackground(new java.awt.Color(204, 204, 204));
        Mostrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Mostrar.setForeground(new java.awt.Color(0, 0, 0));
        Mostrar.setText("(-.-)");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        jPanel2.add(Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 50));

        LogIn.setBackground(new java.awt.Color(102, 102, 102));
        LogIn.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        LogIn.setForeground(new java.awt.Color(204, 204, 204));
        LogIn.setText("Cancelar");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        jPanel2.add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 150, 50));

        Titulo.setFont(new java.awt.Font("Sitka Text", 0, 30)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 204, 204));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Seleccione la cuenta:");
        jPanel2.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, 420, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Pequeño.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        LogIn1.setBackground(new java.awt.Color(102, 102, 102));
        LogIn1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        LogIn1.setForeground(new java.awt.Color(204, 204, 204));
        LogIn1.setText("Buscar");
        LogIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn1ActionPerformed(evt);
            }
        });
        jPanel2.add(LogIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        // TODO add your handling code here:
        if(Mostrar.isSelected()){
            TextoContra.setEchoChar((char) 0);
            TextoContra.requestFocus();
            Mostrar.setText("(0.0)");
        }else{
            TextoContra.setEchoChar(caracter);
            Mostrar.setText("(-.-)");
        }
    }//GEN-LAST:event_MostrarActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_LogInActionPerformed

    private void LogIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn1ActionPerformed
        // TODO add your handling code here:
        Usuarios.Usuario usuario = Inicializador.GestorUsuarios.BusquedaUsuario
        (TextoUsuario.getText(), TextoContra.getText());
        if(usuario != null){
            if(caso == false && !usuario.getUsername().equals("admin")){
                EleccionDeCuenta inicio = new EleccionDeCuenta(null,true,usuario, caso,
                        Inicializador.GestorUsuarios.indice(usuario));
                inicio.setLocationRelativeTo(this);
                inicio.setVisible(true);
                this.dispose();
            }else if(!usuario.getUsername().equals("admin")){
                String[] opciones = {"Si", "No"};
               var selection = JOptionPane.showOptionDialog(null, 
                        "¿Seguro quieres eliminar la cuenta?", "Java Ticket",
                        0, 2, null, opciones, opciones[0]);
                if(selection == 0 ){
                    Inicializador.GestorUsuarios.EliminarUsuario(usuario);
                    if(usuario.equals(UsuarioIngresado)){
                        LogIn inicio = new LogIn();
                        inicio.setLocationRelativeTo(null);
                        inicio.setVisible(true);
                        menu.dispose();
                    }
                    this.dispose();
                }else{
                    this.dispose();
                }
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "La cuenta admin es intocable.");
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(null, "ERROR: USUARIO O CONTRASEÑA INVÁLIDA");
        }
    }//GEN-LAST:event_LogIn1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogIn;
    private javax.swing.JButton LogIn1;
    private javax.swing.JToggleButton Mostrar;
    private javax.swing.JPasswordField TextoContra;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
