
package Swing.AdminUsr;
import Swing.Inicializador;
import Usuarios.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jomel
 */
public class CreacionYEdicionUsr extends javax.swing.JDialog {
    private boolean Caso;
    private int tipo;
    private int pos;
    /**
     * Creates new form CreacionYEdicion
     */
    public CreacionYEdicionUsr(java.awt.Frame parent, boolean modal, boolean caso, int tipo, Usuario usuario , int pos) {
        super(parent, modal);
        Caso = caso;
        this.tipo =  tipo;
        this.pos = pos;
        initComponents();
        
        if(usuario != null){
            TextoEdad.setText(Integer.toString(usuario.getEdad()));
            TextoContra.setText(usuario.getContra());
            TextoUsuario.setText(usuario.getUsername());
            TextoNombre.setText(usuario.getNombre());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        BtConfirmar = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Contra = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        TextoUsuario = new javax.swing.JTextField();
        TextoEdad = new javax.swing.JTextField();
        TextoContra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Java Ticket");
        setBackground(new java.awt.Color(255, 153, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 204, 204));
        String titulo;
        if(Caso == true){
            titulo = "Creación de Usuario";
        }else{
            titulo = "Edición de Usuario";
        }
        Titulo.setText(titulo);
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 30));

        BtConfirmar.setBackground(new java.awt.Color(102, 102, 102));
        BtConfirmar.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        BtConfirmar.setForeground(new java.awt.Color(204, 204, 204));
        BtConfirmar.setText("Confirmar");
        BtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(BtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        BtCancelar.setBackground(new java.awt.Color(102, 102, 102));
        BtCancelar.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        BtCancelar.setForeground(new java.awt.Color(204, 204, 204));
        BtCancelar.setText("Cancelar");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 110, -1));

        Nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(204, 204, 204));
        Nombre.setText("Nombre:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Usuario.setText("Nombre de Usuario:");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        Contra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Contra.setForeground(new java.awt.Color(204, 204, 204));
        Contra.setText("Contraseña:");
        jPanel1.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        Edad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Edad.setForeground(new java.awt.Color(204, 204, 204));
        Edad.setText("Edad:");
        jPanel1.add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        TextoNombre.setBackground(new java.awt.Color(30, 30, 30));
        TextoNombre.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        TextoNombre.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(TextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 240, 40));

        TextoUsuario.setBackground(new java.awt.Color(30, 30, 30));
        TextoUsuario.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        TextoUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(TextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 260, 40));

        TextoEdad.setBackground(new java.awt.Color(30, 30, 30));
        TextoEdad.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        TextoEdad.setForeground(new java.awt.Color(204, 204, 204));
        TextoEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextoEdadKeyTyped(evt);
            }
        });
        jPanel1.add(TextoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 90, 40));

        TextoContra.setBackground(new java.awt.Color(30, 30, 30));
        TextoContra.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        TextoContra.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(TextoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 340, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Pequeño.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConfirmarActionPerformed
        // TODO add your handling code here:
        if(camposvacios() == true){
            int edad = Integer.parseInt(TextoEdad.getText());
            switch(tipo){
                case 1:
                    Administrador usuario1 = new Administrador(edad,
                            TextoNombre.getText(), TextoContra.getText(),
                            TextoUsuario.getText());
                    if(Caso == true){
                        if(Inicializador.GestorUsuarios.agregarUsuario(usuario1) == true){
                        JOptionPane.showMessageDialog(null,
                                "Usuario creado con exito.");
                        this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null,
                                    "ERROR: Ese nombre de usuario ya existe.");
                        }
                    }else{
                        if(Inicializador.usuario.equals(usuario1)){
                            Inicializador.usuario = usuario1;
                        }
                        Inicializador.GestorUsuarios.EditarUsuario(usuario1, pos);
                        JOptionPane.showMessageDialog(null,
                                    "Usuario editado con exito.");
                        this.dispose();
                    }
                    break;
                case 2:
                    DeContenido usuario2 = new DeContenido(edad,
                            TextoNombre.getText(), TextoContra.getText(),
                            TextoUsuario.getText());
                    if(Caso == true){
                        if(Inicializador.GestorUsuarios.agregarUsuario(usuario2) == true){
                        JOptionPane.showMessageDialog(null,
                                "Usuario creado con exito.");
                        this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null,
                                    "ERROR: Ese nombre de usuario ya existe.");
                        }
                    }else{
                        if(Inicializador.usuario.equals(usuario2)){
                            Inicializador.usuario = usuario2;
                        }
                        Inicializador.GestorUsuarios.EditarUsuario(usuario2, pos);
                        JOptionPane.showMessageDialog(null,
                                    "Usuario editado con exito.");
                        this.dispose();
                    }
                    break;
                case 3:
                    Limitado usuario3 = new Limitado(edad,TextoNombre.getText()
                            ,TextoContra.getText(),
                            TextoUsuario.getText());
                    if(Caso == true){
                        if(Inicializador.GestorUsuarios.agregarUsuario(usuario3) == true){
                        JOptionPane.showMessageDialog(null,
                                "Usuario creado con exito.");
                        this.dispose();
                    }else{
                            JOptionPane.showMessageDialog(null,
                                    "ERROR: Ese nombre de usuario ya existe.");
                        }
                    }else{
                        if(Inicializador.usuario.equals(usuario3)){
                            Inicializador.usuario = usuario3;
                        }
                        Inicializador.GestorUsuarios.EditarUsuario(usuario3, pos);
                        JOptionPane.showMessageDialog(null,
                                    "Usuario editado con exito.");
                        this.dispose();
                    }
                    break;        
            }
        }else if(camposvacios() == false){
            JOptionPane.showMessageDialog(null,
                                "ERROR: Tiene algun campo vacío.");
        }else{
            JOptionPane.showMessageDialog(null,
                                "ERROR: No agrego una edad válida");
        }    
    }//GEN-LAST:event_BtConfirmarActionPerformed

    private void TextoEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoEdadKeyTyped
        // TODO add your handling code here:
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;

        if(!valido){
            evt.consume();
        }
    }//GEN-LAST:event_TextoEdadKeyTyped
 
    public boolean camposvacios(){
        return !TextoContra.getText().trim().isEmpty() && !TextoNombre.getText().trim().isEmpty() &&
                !TextoUsuario.getText().trim().isEmpty() && !TextoEdad.getText().trim().isEmpty();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtConfirmar;
    private javax.swing.JLabel Contra;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField TextoContra;
    private javax.swing.JTextField TextoEdad;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoUsuario;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
