
package Swing.AdminRep;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author jomel
 */
public class Grafica extends javax.swing.JPanel {

    private double deporte, musica, religioso;
    public Grafica(double deporte, double musica, double religioso) {
        initComponents();
        this.musica = musica;
        this.deporte = deporte;
        this.religioso = religioso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public double maxVal(double rojo, double verde, double azul){
        if(rojo > verde && rojo > azul){
            return rojo; 
        }else if(verde > azul){
            return verde;
        }
        return azul;
    }
    
    public void paint(Graphics g){
        super.paint(g);
            
            double maxValor = maxVal(musica,religioso, deporte);
            int escala = (int) (maxValor/4);
            
            int largo_rojo = (int) (deporte * 100/maxValor);
            int largo_verde = (int) (musica * 100/maxValor);
            int largo_azul = (int) (religioso * 100/maxValor);
            
            g.setColor(Color.red);
            g.fillRect(65, 20, largo_rojo, 20);
            g.drawString("Deportivo", 10, 30);
            g.setColor(Color.green);
            g.fillRect(65, 55, largo_verde, 20);
            g.drawString("Musical", 10, 65);
            g.setColor(Color.blue);
            g.fillRect(65 ,86, largo_azul, 20);
            g.drawString("Religioso", 10, 100);
            
            for(int i=1; i<=3;i++){
                g.setColor(Color.black);
                if(i == 1)
                    g.drawString("0", 65, 120);
                
                g.drawString(Integer.toString(escala*(i-1)), 20*i + 65, 9*i+120);
            }
            g.drawString(Integer.toString((int)maxValor), 155, 156);
    }
}
