
package Swing.Menu;

import Swing.AdminEvt.EleccionDeCodigo;
import Swing.AdminEvt.EleccionDeEvento;
import javax.swing.JOptionPane;

/**
 *
 * @author jomel
 */
public class AdminEvt extends javax.swing.JPanel {

    public Menu menu;
    public AdminEvt(Menu menu) {
        initComponents();
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminEvt = new javax.swing.JPanel();
        Titulo4 = new javax.swing.JLabel();
        CrearEvt = new javax.swing.JButton();
        EditarEvt = new javax.swing.JButton();
        VerEvento = new javax.swing.JButton();
        BorrarEvt1 = new javax.swing.JButton();

        AdminEvt.setBackground(new java.awt.Color(51, 51, 51));
        AdminEvt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo4.setFont(new java.awt.Font("Sitka Banner", 0, 36)); // NOI18N
        Titulo4.setForeground(new java.awt.Color(204, 204, 204));
        Titulo4.setText("Administrador de Eventos");
        AdminEvt.add(Titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        CrearEvt.setBackground(new java.awt.Color(102, 102, 102));
        CrearEvt.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        CrearEvt.setForeground(new java.awt.Color(204, 204, 204));
        CrearEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evento.png"))); // NOI18N
        CrearEvt.setText("Crear");
        CrearEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEvtActionPerformed(evt);
            }
        });
        AdminEvt.add(CrearEvt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 100));

        EditarEvt.setBackground(new java.awt.Color(102, 102, 102));
        EditarEvt.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        EditarEvt.setForeground(new java.awt.Color(204, 204, 204));
        EditarEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evento.png"))); // NOI18N
        EditarEvt.setText("Editar");
        EditarEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEvtActionPerformed(evt);
            }
        });
        AdminEvt.add(EditarEvt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 180, 100));

        VerEvento.setBackground(new java.awt.Color(102, 102, 102));
        VerEvento.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        VerEvento.setForeground(new java.awt.Color(204, 204, 204));
        VerEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evento.png"))); // NOI18N
        VerEvento.setText("Ver Eventos");
        VerEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEventoActionPerformed(evt);
            }
        });
        AdminEvt.add(VerEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 210, 100));

        BorrarEvt1.setBackground(new java.awt.Color(102, 102, 102));
        BorrarEvt1.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        BorrarEvt1.setForeground(new java.awt.Color(204, 204, 204));
        BorrarEvt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Evento.png"))); // NOI18N
        BorrarEvt1.setText("Borrar");
        BorrarEvt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarEvt1ActionPerformed(evt);
            }
        });
        AdminEvt.add(BorrarEvt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 170, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminEvt, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminEvt, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEvtActionPerformed
        // TODO add your handling code here:
        if(Swing.Inicializador.usuario.esLimitado() == true){
            JOptionPane.showMessageDialog(null, "Su usuario no posee permisos para esta acción.");
        }else{
            EleccionDeEvento inicio = new EleccionDeEvento(menu,true, null);
            inicio.setLocationRelativeTo(menu);
            inicio.setVisible(true);
        }
    }//GEN-LAST:event_CrearEvtActionPerformed

    private void EditarEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEvtActionPerformed
        // TODO add your handling code here
        if(Swing.Inicializador.usuario.esLimitado() == true){
            JOptionPane.showMessageDialog(null, "Su usuario no posee permisos para esta acción.");
        }else{
            EleccionDeCodigo inicio = new EleccionDeCodigo(null,true, null);
            inicio.setLocationRelativeTo(menu);
            inicio.setVisible(true);
        }
    }//GEN-LAST:event_EditarEvtActionPerformed

    private void VerEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEventoActionPerformed
        // TODO add your handling code here:
        Swing.AdminEvt.EleccionVerEvento inicio = new Swing.AdminEvt.EleccionVerEvento(null,true);
            inicio.setLocationRelativeTo(menu);
            inicio.setVisible(true);
    }//GEN-LAST:event_VerEventoActionPerformed

    private void BorrarEvt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarEvt1ActionPerformed
        // TODO add your handling code here:
        if(Swing.Inicializador.usuario.esLimitado() == true){
            JOptionPane.showMessageDialog(null, "Su usuario no posee permisos para esta acción.");
        }else{
            EleccionDeCodigo inicio = new EleccionDeCodigo(null,true, Swing.Inicializador.usuario);
            inicio.setLocationRelativeTo(menu);
            inicio.setVisible(true);
        }
    }//GEN-LAST:event_BorrarEvt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminEvt;
    private javax.swing.JButton BorrarEvt1;
    private javax.swing.JButton CrearEvt;
    private javax.swing.JButton EditarEvt;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JButton VerEvento;
    // End of variables declaration//GEN-END:variables
}
