/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Swing.Menu;

/**
 *
 * @author jomel
 */
public class AdminRep extends javax.swing.JPanel {

    /**
     * Creates new form AdminRep
     */
    public AdminRep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SistemaRep = new javax.swing.JPanel();
        Titulo5 = new javax.swing.JLabel();
        FutRep = new javax.swing.JButton();
        RealRep = new javax.swing.JButton();
        FechRep = new javax.swing.JButton();
        CancelEvt = new javax.swing.JButton();
        RepPerfil = new javax.swing.JButton();

        SistemaRep.setBackground(new java.awt.Color(51, 51, 51));

        Titulo5.setFont(new java.awt.Font("Sitka Banner", 0, 48)); // NOI18N
        Titulo5.setForeground(new java.awt.Color(204, 204, 204));
        Titulo5.setText("Sistema de Reportes");

        FutRep.setBackground(new java.awt.Color(102, 102, 102));
        FutRep.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        FutRep.setForeground(new java.awt.Color(204, 204, 204));
        FutRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N
        FutRep.setText("Eventos Futuros");
        FutRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FutRepActionPerformed(evt);
            }
        });

        RealRep.setBackground(new java.awt.Color(102, 102, 102));
        RealRep.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        RealRep.setForeground(new java.awt.Color(204, 204, 204));
        RealRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N
        RealRep.setText("Eventos Realizados");
        RealRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealRepActionPerformed(evt);
            }
        });

        FechRep.setBackground(new java.awt.Color(102, 102, 102));
        FechRep.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        FechRep.setForeground(new java.awt.Color(204, 204, 204));
        FechRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N
        FechRep.setText("Generado por Fecha");
        FechRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechRepActionPerformed(evt);
            }
        });

        CancelEvt.setBackground(new java.awt.Color(102, 102, 102));
        CancelEvt.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        CancelEvt.setForeground(new java.awt.Color(204, 204, 204));
        CancelEvt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N
        CancelEvt.setText("Eventos Cancelados");
        CancelEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelEvtActionPerformed(evt);
            }
        });

        RepPerfil.setBackground(new java.awt.Color(102, 102, 102));
        RepPerfil.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        RepPerfil.setForeground(new java.awt.Color(204, 204, 204));
        RepPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        RepPerfil.setText("Ver Perfil");
        RepPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SistemaRepLayout = new javax.swing.GroupLayout(SistemaRep);
        SistemaRep.setLayout(SistemaRepLayout);
        SistemaRepLayout.setHorizontalGroup(
            SistemaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SistemaRepLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RepPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
            .addGroup(SistemaRepLayout.createSequentialGroup()
                .addGroup(SistemaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SistemaRepLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(SistemaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CancelEvt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FutRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(SistemaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechRep)
                            .addComponent(RealRep, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SistemaRepLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Titulo5)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        SistemaRepLayout.setVerticalGroup(
            SistemaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaRepLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Titulo5)
                .addGap(38, 38, 38)
                .addGroup(SistemaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FutRep)
                    .addComponent(RealRep))
                .addGap(54, 54, 54)
                .addGroup(SistemaRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechRep)
                    .addComponent(CancelEvt))
                .addGap(38, 38, 38)
                .addComponent(RepPerfil)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SistemaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SistemaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FutRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FutRepActionPerformed
        // TODO add your handling code here:
        Swing.AdminRep.AdminRep inicio = new Swing.AdminRep.AdminRep(1);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_FutRepActionPerformed

    private void RealRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealRepActionPerformed
        // TODO add your handling code here:
        Swing.AdminRep.AdminRep inicio = new Swing.AdminRep.AdminRep(2);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_RealRepActionPerformed

    private void FechRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechRepActionPerformed
        // TODO add your handling code here:
        Swing.AdminRep.AdminRep inicio = new Swing.AdminRep.AdminRep(4);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_FechRepActionPerformed

    private void CancelEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelEvtActionPerformed
        // TODO add your handling code here:
        Swing.AdminRep.AdminRep inicio = new Swing.AdminRep.AdminRep(3);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_CancelEvtActionPerformed

    private void RepPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepPerfilActionPerformed
        // TODO add your handling code here:
        Swing.AdminRep.AdminRep inicio = new Swing.AdminRep.AdminRep(5);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_RepPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelEvt;
    private javax.swing.JButton FechRep;
    private javax.swing.JButton FutRep;
    private javax.swing.JButton RealRep;
    private javax.swing.JButton RepPerfil;
    private javax.swing.JPanel SistemaRep;
    private javax.swing.JLabel Titulo5;
    // End of variables declaration//GEN-END:variables
}
