
package Swing.Menu;

import Swing.AdminUsr.BuscadorDeUsuario;
import Swing.AdminUsr.EleccionDeCuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author jomel
 */
public class AdminUsr extends javax.swing.JPanel {
    
    Menu menu;
    /**
     * Creates new form AdminUsr
     */
    public AdminUsr(Menu menu) {
        initComponents();
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminUsr = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        CrearUsr = new javax.swing.JButton();
        EditarUsr = new javax.swing.JButton();
        BorrarUsr = new javax.swing.JButton();

        AdminUsr.setBackground(new java.awt.Color(51, 51, 51));
        AdminUsr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Sitka Banner", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 204, 204));
        Titulo.setText("Administrador de Usuarios");
        AdminUsr.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        CrearUsr.setBackground(new java.awt.Color(102, 102, 102));
        CrearUsr.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        CrearUsr.setForeground(new java.awt.Color(204, 204, 204));
        CrearUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        CrearUsr.setText("Crear");
        CrearUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsrActionPerformed(evt);
            }
        });
        AdminUsr.add(CrearUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 100));

        EditarUsr.setBackground(new java.awt.Color(102, 102, 102));
        EditarUsr.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        EditarUsr.setForeground(new java.awt.Color(204, 204, 204));
        EditarUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        EditarUsr.setText("Editar");
        EditarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsrActionPerformed(evt);
            }
        });
        AdminUsr.add(EditarUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 180, 100));

        BorrarUsr.setBackground(new java.awt.Color(102, 102, 102));
        BorrarUsr.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        BorrarUsr.setForeground(new java.awt.Color(204, 204, 204));
        BorrarUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        BorrarUsr.setText("Borrrar");
        BorrarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarUsrActionPerformed(evt);
            }
        });
        AdminUsr.add(BorrarUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsrActionPerformed
        // TODO add your handling code here:
        if(!Swing.Inicializador.usuario.esLimitado()){
            EleccionDeCuenta inicio = new EleccionDeCuenta(null, true, null,true,0);
            inicio.setLocationRelativeTo(menu);
            inicio.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Su usuario no posee permisos para esta acción.");
        }
    }//GEN-LAST:event_CrearUsrActionPerformed

    private void EditarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsrActionPerformed
        // TODO add your handling code here:
        if(!Swing.Inicializador.usuario.esLimitado()){
            BuscadorDeUsuario inicio = new BuscadorDeUsuario(null, true, false, Swing.Inicializador.usuario, menu);
        inicio.setVisible(true);
        inicio.setLocationRelativeTo(menu);
        }else{
            JOptionPane.showMessageDialog(null, "Su usuario no posee permisos para esta acción.");
        }
    }//GEN-LAST:event_EditarUsrActionPerformed

    private void BorrarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarUsrActionPerformed
        // TODO add your handling code here:
        if(!Swing.Inicializador.usuario.esLimitado()){
            BuscadorDeUsuario inicio = new BuscadorDeUsuario(null, true, true, Swing.Inicializador.usuario, menu);
        inicio.setVisible(true);
        inicio.setLocationRelativeTo(menu);
        }else{
            JOptionPane.showMessageDialog(null, "Su usuario no posee permisos para esta acción.");
        }
    }//GEN-LAST:event_BorrarUsrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminUsr;
    private javax.swing.JButton BorrarUsr;
    private javax.swing.JButton CrearUsr;
    private javax.swing.JButton EditarUsr;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
